# Generated by Django 5.1.1 on 2024-09-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(default=1, upload_to="Images"),
            preserve_default=False,
        ),
    ]
