# Generated by Django 5.1.1 on 2024-09-07 02:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0002_blog_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="image",
        ),
    ]
